version: '3'
services:
  tile38:
    image: tile38/tile38
    container_name: tile38
    ports:
        - 9851:9851
    restart: unless-stopped
  vue-deckgl:
    container_name: vue-deckgl
    build:
      context: ./vue-deckgl
      dockerfile: Dockerfile
    volumes:
      - './vue-deckgl/:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'