apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  # creationTimestamp: null
  labels:
    io.kompose.service: tile38
  name: tile38
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tile38
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      # creationTimestamp: null
      labels:
        io.kompose.service: tile38
    spec:
      containers:
        - image: tile38/tile38
          name: tile38
          ports:
            - containerPort: 9851
          resources: {}
      restartPolicy: Always
status: {}
