apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  labels:
    io.kompose.service: vue-deckgl-claim0
  name: vue-deckgl-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
